### ISSUE TITLE
GPL and "additionally".

### ISSUE THREAD

**Issue by andre-caldas** [pthom/litgen#18]
I've just heard about this fantastic project on the pygen11 documentation page. I was reading the [documentation](https://pthom.github.io/litgen/litgen_book/00_00_intro.html) and one thing bothers me a little.

About the software license... although I do totally understand the intentions and idea, litgen's documentation states:
> The [litgen project](https://github.com/pthom/litgen) is published under the [GNU General Public License, version 3](https://raw.githubusercontent.com/pthom/litgen/main/LICENSE.txt).
>
> Additionally, you may not pretend that you wrote this software. If you use it inside a program, or if you distribute code generated by it in a program or in a library, you must acknowledge somewhere in your documentation that you have used the litgen project.

Except for the "AGPL clause", the GPLv3 does not allow "further restrictions" (as in "additionally"). There is no problem in saying "you may not pretend that you wrote this software", because it is redundant. It is probably illegal almost everywhere if you pretend you wrote a software you didn't.

However, the part after that is IMO in violation of the GPLv3, under which srcML is distributed:
> [...] if you distribute code generated by it in a program or in a library, you must acknowledge somewhere in your documentation that you have used the litgen project.

I would suggest substituting this text by a nice request, asking for an (optional) acknowledgement. :-)

**Comment by pthom** [comment]
Hello,

Thanks for contacting me! I am not a specialist in open source licensing, although I did publish quite a few libraries under several licenses (MIT, GPLV3).

This library was a very, very long endeavor, and  the work hours are in the thousands. 
Anyhow, this is not the subject. I would like your opinion on something I found inside GPLV3:

```
  7. Additional Terms.

  "Additional permissions" are terms that supplement the terms of this
License by making exceptions from one or more of its conditions.
Additional permissions that are applicable to the entire Program shall
be treated as though they were included in this License, to the extent
that they are valid under applicable law.  If additional permissions
apply only to part of the Program, that part may be used separately
under those permissions, but the entire Program remains governed by
this License without regard to the additional permissions.

  When you convey a copy of a covered work, you may at your option
remove any additional permissions from that copy, or from any part of
it.  (Additional permissions may be written to require their own
removal in certain cases when you modify the work.)  You may place
additional permissions on material, added by you to a covered work,
for which you have or can give appropriate copyright permission.

  Notwithstanding any other provision of this License, for material you
add to a covered work, you may (if authorized by the copyright holders of
that material) supplement the terms of this License with terms:

    a) Disclaiming warranty or limiting liability differently from the
    terms of sections 15 and 16 of this License; or

    b) Requiring preservation of specified reasonable legal notices or
    author attributions in that material or in the Appropriate Legal
    Notices displayed by works containing it; or

    c) Prohibiting misrepresentation of the origin of that material, or
    requiring that modified versions of such material be marked in
    reasonable ways as different from the original version; or

    d) Limiting the use for publicity purposes of names of licensors or
    authors of the material; or

    e) Declining to grant rights under trademark law for use of some
    trade names, trademarks, or service marks; or

    f) Requiring indemnification of licensors and authors of that
    material by anyone who conveys the material (or modified versions of
    it) with contractual assumptions of liability to the recipient, for
    any liability that these contractual assumptions directly impose on
    those licensors and authors.
```

IMHO, part 7b:
>   b) Requiring preservation of specified reasonable legal notices or
>    author attributions in that material or in the Appropriate Legal
>    Notices displayed by works containing it; or

is not that far from what I wrote.

Thoughts?

**Comment by andre-caldas** [comment]
First of all, I'd like to thank you for being so open minded about my "issue". :-)

> IMHO, part 7b:
> 
> > b) Requiring preservation of specified reasonable legal notices or
> > author attributions in that material or in the Appropriate Legal
> > Notices displayed by works containing it; or
> 
> is not that far from what I wrote.
> 
> Thoughts?

Notice that "that material" means the code you wrote. So, you can ask people to preserve those "legal notices or author attributions" in litgen. This leaves the remaining and more difficult to understand:
> [...] or in the Appropriate Legal Notices displayed by works containing it

In that case, I think that if some copyrighted work contains litgen, you can ask them to acknowledge so.

But I am concerned about this:
> [...] or if you distribute **code generated by it** in a program or in a library, you must acknowledge somewhere in your documentation that you have used the litgen project.

Central questions:
1. Do you believe that code generated by litgen is part of the litgen?
2. Do you believe the generated code is, for example, a derivative of its template?
3. Does the GPL in srcML allow impositions on the use of generated code?

With a little exaggeration, it is like if gcc people demanded acknowledgement of gcc because it was used to compile the program.

Any way, even if it was allowed (I do believe it is not)... even then, you might find it much nicer to just ask for acknowledgement, even in cases you could impose it if you wanted.

I will certainly acknowledge it if I end up using it. Right now, I am evaluating the alternatives. (feel free to write to me and explain why litgen is so superior) ;-)

When the GPLv3 was designed, one of the goals was to make it easier to mix with works licensed with other free licenses. For that reason it has this section "7. Additional Terms". For me, personally, this is not something we should use when not needed. It is something you should use when you want to combine copyrighted materials and one of them GPLv3 and the other, although usually quite permissible, like the MIT license, might demand some small reasonable thing mentioned in section 7.

The more Additional Terms the more complicated the licensing becomes.

**Comment by pthom** [comment]
Hi, I updated the license part. It is now simpler.

> Right now, I am evaluating the alternatives. (feel free to write to me and explain why litgen is so superior) ;-)

Well, I don't know of any alternative that offers such usable binding in terms of discoverability (with documented stubs), and such a range of possible customizations. But I'm biased, and I'll let you try it, and hopefully [share your experience if you end up using it](https://github.com/pthom/litgen/discussions/19)
