### ISSUE TITLE
Pydef Error with Overloaded Const Methods in Generated Code

### ISSUE THREAD

**Issue by sacha-renault** [pthom/litgen#22]
### Version: 0.11.0

The litgen library generates incorrect binding code for overloaded const methods. Specifically, the generated py::overload_cast does not include the py::const_ qualifier for methods that are const-qualified.

#### C++ Class
```
class Dummy {
public:
    Dummy(int v) : value(v) {}

    // Overloaded methods with const qualifiers
    int compute(int a) const {
        return value + a;
    }

    int compute(const Dummy& other) const {
        return value + other.value;
    }

private:
    int value;
};
```

#### Code Generated by Litgen 
```
auto pyClassDummy =
    py::class_<Dummy>
        (m, "Dummy", "")
    .def(py::init<int>(), py::arg("v"))
    .def("compute",
        py::overload_cast<int>(&Dummy::compute),  // Missing `py::const_`
        py::arg("a"),
        "Overloaded methods with const qualifiers")
    .def("compute",
        py::overload_cast<const Dummy &>(&Dummy::compute), py::arg("other"));
```

#### Correct Code
The generated code should include `py::const_` to correctly bind const-qualified methods:
```
auto pyClassDummy =
    py::class_<Dummy>
        (m, "Dummy", "")
    .def(py::init<int>(), py::arg("v"))
    .def("compute",
        py::overload_cast<int>(&Dummy::compute, py::const_),  // Fixed
        py::arg("a"),
        "Overloaded methods with const qualifiers")
    .def("compute",
        py::overload_cast<const Dummy &>(&Dummy::compute, py::const_),  // Fixed
        py::arg("other"));
```

Without py::const_, the py::overload_cast call fails to match the function signature of const-qualified methods, resulting in compilation errors.

**Comment by pthom** [comment]
Bonjour,

Here is the code generated by the current version:

```cpp
    py::class_<Dummy>
        (m, "Dummy", "")
    .def(py::init<int>(),
        py::arg("v"))
    .def("compute",
        py::overload_cast<int>(&Dummy::compute, py::const_), py::arg("a"))
    .def("compute",
        py::overload_cast<const Dummy &>(&Dummy::compute, py::const_), py::arg("other"))
    ;
```

i.e. it is correct.

I'm surprised your are mentioning "Version: 0.11.0". I did not release any numbered version of litgen on GitHub or pypi:  
litgen is intended to be used by installing it from source. The version number mentioned in pyproject.toml is meaningless at the moment.

Where did you get this version 0.11.0?

If you have time, I'd be interested in having more information about the context in which you are using litgen, as I'm always happy to learn what other people are doing with it!

Thanks

**Comment by pthom** [comment]
See 226992d

**Comment by sacha-renault** [comment]
_Bonjour_!  

### The Bug  
I initially installed `litgen` using the version available on [PyPI](https://pypi.org/project/litgen/) rather than the `pip install "litgen@git+https://github.com/pthom/litgen"` method recommended in the docs.  
Switching to the Git installation resolved the issue, so I assume the PyPI version isn't up-to-date.  

### The Version  
`pip show litgen` showed version `0.11.0`.  

I've always used the basic `pip install litgen` method without problems before, so this was my oversight. I should have investigated further before opening an issue—my apologies for any confusion!  

Thanks for the prompt reply, and sorry again for raising a non-issue.
