### ISSUE TITLE
How to disable comments or use pybind11 literals

### ISSUE THREAD

**Issue by nnop** [pthom/litgen#4]
Hi, Thanks for the great tool. It can save me a lot of tedious work when binding C++ code.
I have two questions:
1. how to disable generating comments with the binding code?  
2. how to use pybind11 literals `_a` instead of `py::arg`?

Didn't find that in the [options](https://github.com/pthom/litgen/blob/main/src/litgen/options.py) code.

**Comment by nnop** [comment]
Could you have a look at this issue? @pthom

**Comment by pthom** [comment]
Hello, 

Thanks for your output.

> how to use pybind11 literals _a instead of py::arg

I do not see the motivation for this, given that this is generated code. Can you please explain why you would want this?
 
If this is to save a few bytes in the generated code, I do not think it is worth the effort.

> how to disable generating comments with the binding code?

Same question, what is your use case? 
Also, are you referring to the comment in the python stubs file, the C++ file, or both?

I do not have time to work on this, but you could try to comment out those lines, which is where the comments are gathered.

https://github.com/pthom/litgen/blob/60514768f6574f3b4d540eb9b479f2c5e5ce4ccf/src/srcmlcpp/internal/srcml_comments.py#L366-L384

**Comment by pthom** [comment]
See https://github.com/pthom/litgen/commit/ebf7c044effe45ae960521a8945f32effd826cb5

**Comment by nnop** [comment]
Thanks for you respondence.

Now I mainly use litgen to generating an initial version of the binding code.

Because many C++ functions exist in the form of output parameters, I need to wrap them with lambda functions, create temporary variables, and return them. 

Also, considering return value policies, there's still some manual modification work involved. Therefore, I hope to start with a relatively simple initialization binding code.
